# Generated by Django 4.2.1 on 2023-08-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_commerce', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
